version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: asso
      POSTGRES_PASSWORD: asso
      POSTGRES_DB: asso
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asso"]
      interval: 10s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://asso:asso@db:5432/asso
      SSH_HOST: 162.19.27.110    # seulement l’adresse
      SSH_PORT: "2222"
      SSH_USER: astroweb         # votre login
      SSH_KEY_PATH: /home/app/.ssh/id_ed25519
    volumes:
      - .:/app:ro
      - /var/run/docker.sock:/var/run/docker.sock
      # monte tout le dossier SSH de votre Windows dans /home/app/.ssh
      - C:\Users\Arthur\.ssh:/home/app/.ssh:r
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  db_data:
