# docker-compose.yml  (sans clé version)
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: astroweb
      POSTGRES_USER: astroweb
      POSTGRES_PASSWORD: astroweb
    ports: ["5432:5432"]
    volumes: ["pg-data:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 3s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        echo '⏳ waiting for postgres...' &&
        until pg_isready -h db -U astroweb; do sleep 1; done &&
        echo '✅ postgres is ready' &&

        flask db upgrade &&
        exec flask run --host=0.0.0.0
      "
    volumes: [".:/app"]
    ports: ["5000:5000"]
    env_file: .env

volumes:
  pg-data:
