version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: asso
      POSTGRES_PASSWORD: asso
      POSTGRES_DB: asso
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asso"]
      interval: 10s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://asso:asso@db:5432/asso
    volumes:
      - .:/app:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  db_data:
